#!/bin/bash
source base

mv $CONFIGFOLDER ~/.shellscripts.tmp/configs/ -R

cd $ROOTFOLDER
git fetch origin
git reset --hard origin/master
git checkout
git pull
chmod 775 $ROOTFOLDER -R
mv ~/.shellscripts.tmp/configs/ $CONFIGFOLDER -R